name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk11'
    - run: |
        python -V
        java -version
        pip3 install requests
    - run: |
        git clone git@github.com:muuklabs/executor.git
        cp key.pub executor
