name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk11'
    - run: |
        python -V
        java -version
        pip3 install requests
    - uses: actions/checkout@v2-beta
      with:
        repository: 'muuklabs/executor'
        path: 'executor'
    - run: cp key.pub executor
    - working-directory: executor
      run: |
        ls
        export DISPLAY=:1
        python mkcli.py -p tag -t TC6550 -browser firefox
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: reports
        path: executor/build/reports
      
